/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AddIcon: typeof import('./src/components/icon/AddIcon.vue')['default']
    CalendarIcon: typeof import('./src/components/icon/CalendarIcon.vue')['default']
    CollapseDetail: typeof import('./src/components/detail/CollapseDetail.vue')['default']
    CompleteIcon: typeof import('./src/components/icon/CompleteIcon.vue')['default']
    DatePickIcon: typeof import('./src/components/icon/DatePickIcon.vue')['default']
    DateTaskList: typeof import('./src/components/detail/DateTaskList.vue')['default']
    DeleteIcon: typeof import('./src/components/icon/DeleteIcon.vue')['default']
    DetailTaskItem: typeof import('./src/components/detail/DetailTaskItem.vue')['default']
    EditIcon: typeof import('./src/components/icon/EditIcon.vue')['default']
    ExpiredDetail: typeof import('./src/components/detail/ExpiredDetail.vue')['default']
    FutureDetail: typeof import('./src/components/detail/FutureDetail.vue')['default']
    LeftArrowIcon: typeof import('./src/components/icon/LeftArrowIcon.vue')['default']
    ListIcon: typeof import('./src/components/icon/ListIcon.vue')['default']
    PageHeader: typeof import('./src/components/struct/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/struct/SideMenu.vue')['default']
    TaskAddCardButton: typeof import('./src/components/form/TaskAddCardButton.vue')['default']
    TaskAddDialogButton: typeof import('./src/components/form/TaskAddDialogButton.vue')['default']
    TaskForm: typeof import('./src/components/form/TaskForm.vue')['default']
    ThemeButton: typeof import('./src/components/button/ThemeButton.vue')['default']
    TimelineIcon: typeof import('./src/components/icon/TimelineIcon.vue')['default']
    TodayDetail: typeof import('./src/components/detail/TodayDetail.vue')['default']
  }
}
